spring:
  application:
    name: Achat
  r2dbc:
    url: r2dbc:mariadb://hk.hjong.cn:3306/one
    username: one
    password: 95aninjv
  mail:
    host: smtp.qq.com
    port: 587
    username: c.jong@qq.com
    password: tsuldibuddardhae
logging:
  level:
    org.springframework.data.r2dbc: INFO  # 设置 r2dbc 日志级别为 INFO 开启sql语句打印

chat:
  proxy:
    host: jp.hjong.cn
    port: 14650
  token:
    secret: 95aninjv
    issuer: hk.hjong.cn
    expires-minute: 43200
  channel:
    strategy: first

#debug: true


